dist: trusty
sudo: false

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

addons:
  postgresql: "9.4"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

env:
  global:
    - LUAROCKS=2.4.3
    - OPENSSL=1.0.2n
    - CASSANDRA=2.2.8
    - OPENRESTY_BASE=1.11.2.5
    - OPENRESTY_LATEST=1.13.6.1
    - OPENRESTY=$OPENRESTY_BASE
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit
    - TEST_SUITE=integration
      KONG_TEST_DATABASE=postgres
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=plugins
      KONG_TEST_DATABASE=postgres
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=integration
      KONG_TEST_DATABASE=cassandra
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=plugins
      KONG_TEST_DATABASE=cassandra
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=integration
      KONG_TEST_DATABASE=cassandra
      CASSANDRA=3.9
      OPENRESTY=$OPENRESTY_LATEST
    - TEST_SUITE=plugins
      KONG_TEST_DATABASE=cassandra
      CASSANDRA=3.9
      OPENRESTY=$OPENRESTY_LATEST

before_install:
  - source .ci/setup_env.sh

install:
  - make dev

script:
  - .ci/run_tests.sh

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
