dist: trusty
sudo: false

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

addons:
  postgresql: "9.4"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

env:
  global:
    - LUAROCKS=2.4.2
    - OPENSSL=1.0.2l
    - CASSANDRA=2.2.8
    - OPENRESTY_BASE=1.11.2.4
    - OPENRESTY_LATEST=1.11.2.4
    - OPENRESTY=$OPENRESTY_BASE
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=unit
    - TEST_SUITE=integration
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=plugins
      OPENRESTY=$OPENRESTY_BASE
    - TEST_SUITE=integration
      OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=3.9
    - TEST_SUITE=plugins
      OPENRESTY=$OPENRESTY_LATEST
      CASSANDRA=3.9

before_install:
  - source .ci/setup_env.sh &> setup.log || (cat setup.log && exit 1)

install:
  - make dev &> install.log || (cat install.log && exit 1)

script:
  - .ci/run_tests.sh &> tests.log || (cat tests.log && exit 1)

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository
